version: '3.7'
services:
 repo:
  image: altemans/repo:1
  container_name: repo
  restart: always
  ports:
   - "8080:80"
  volumes:
   - /repo/repo:/var/www/html:rw
   - /repo/repo-load:/newload/:rw
